// Gulf Embedded Accounting Platform — Platform Mock Data
// DEMO DATA FOR DEVELOPMENT — Replace with real API calls

import {
  GulfCountryConfig, IndustryTemplate, PlanConfig,
  FinancialHealthScore, BusinessInsight, ApiKey, Webhook,
  SandboxEnvironment,
} from '../types/platform';

// ═══════════════════════════════════════════════════════════════════
// GULF COUNTRIES CONFIGURATION
// ═══════════════════════════════════════════════════════════════════

export const GULF_COUNTRIES: GulfCountryConfig[] = [
  {
    code: 'KW',
    nameAr: 'الكويت',
    nameEn: 'Kuwait',
    currency: 'KWD',
    currencyAr: 'دينار كويتي',
    currencySymbol: 'د.ك',
    currencyDecimals: 3,
    vatRate: 0,
    hasVat: false,
    fiscalYearStart: 'Jan',
    invoiceRequirements: {
      requiresQrCode: false,
      requiresTaxNumber: false,
      requiresCRNumber: true,
      requiresSequentialNumber: true,
      requiresBuyerDetails: false,
      digitalSignature: false,
      reportingToAuthority: false,
      retentionYears: 10,
    },
    taxAuthority: 'Ministry of Finance Kuwait',
    taxAuthorityAr: 'وزارة المالية الكويتية',
    complianceNotes: 'No VAT. Commercial registration required.',
    complianceNotesAr: 'لا تطبق ضريبة القيمة المضافة. السجل التجاري مطلوب.',
    phonePrefix: '+965',
    supportedPaymentMethods: ['knet', 'visa', 'mastercard', 'amex', 'cash', 'bank_transfer'],
  },
  {
    code: 'SA',
    nameAr: 'المملكة العربية السعودية',
    nameEn: 'Saudi Arabia',
    currency: 'SAR',
    currencyAr: 'ريال سعودي',
    currencySymbol: 'ر.س',
    currencyDecimals: 2,
    vatRate: 0.15,
    hasVat: true,
    fiscalYearStart: 'Jan',
    invoiceRequirements: {
      requiresQrCode: true,
      requiresTaxNumber: true,
      requiresCRNumber: true,
      requiresSequentialNumber: true,
      requiresBuyerDetails: true,
      digitalSignature: true,
      reportingToAuthority: true,
      retentionYears: 10,
    },
    taxAuthority: 'ZATCA',
    taxAuthorityAr: 'هيئة الزكاة والضريبة والجمارك',
    complianceNotes: 'VAT 15%. E-invoicing (ZATCA Phase 2) mandatory.',
    complianceNotesAr: 'ضريبة القيمة المضافة 15%. الفوترة الإلكترونية إلزامية (هيئة زاتكا المرحلة الثانية).',
    phonePrefix: '+966',
    supportedPaymentMethods: ['mada', 'visa', 'mastercard', 'stc_pay', 'cash', 'bank_transfer'],
  },
  {
    code: 'AE',
    nameAr: 'الإمارات العربية المتحدة',
    nameEn: 'United Arab Emirates',
    currency: 'AED',
    currencyAr: 'درهم إماراتي',
    currencySymbol: 'د.إ',
    currencyDecimals: 2,
    vatRate: 0.05,
    hasVat: true,
    fiscalYearStart: 'Jan',
    invoiceRequirements: {
      requiresQrCode: false,
      requiresTaxNumber: true,
      requiresCRNumber: true,
      requiresSequentialNumber: true,
      requiresBuyerDetails: false,
      digitalSignature: false,
      reportingToAuthority: false,
      retentionYears: 5,
    },
    taxAuthority: 'FTA — Federal Tax Authority',
    taxAuthorityAr: 'الهيئة الاتحادية للضرائب',
    complianceNotes: 'VAT 5%. TRN required on invoices above AED 10,000.',
    complianceNotesAr: 'ضريبة القيمة المضافة 5%. رقم التسجيل الضريبي مطلوب للفواتير أعلى من 10,000 درهم.',
    phonePrefix: '+971',
    supportedPaymentMethods: ['visa', 'mastercard', 'amex', 'cash', 'bank_transfer'],
  },
  {
    code: 'QA',
    nameAr: 'قطر',
    nameEn: 'Qatar',
    currency: 'QAR',
    currencyAr: 'ريال قطري',
    currencySymbol: 'ر.ق',
    currencyDecimals: 2,
    vatRate: 0,
    hasVat: false,
    fiscalYearStart: 'Jan',
    invoiceRequirements: {
      requiresQrCode: false,
      requiresTaxNumber: false,
      requiresCRNumber: true,
      requiresSequentialNumber: true,
      requiresBuyerDetails: false,
      digitalSignature: false,
      reportingToAuthority: false,
      retentionYears: 7,
    },
    taxAuthority: 'General Tax Authority Qatar',
    taxAuthorityAr: 'الهيئة العامة للضرائب القطرية',
    complianceNotes: 'No VAT. Commercial registration required.',
    complianceNotesAr: 'لا تطبق ضريبة القيمة المضافة. السجل التجاري مطلوب.',
    phonePrefix: '+974',
    supportedPaymentMethods: ['visa', 'mastercard', 'cash', 'bank_transfer'],
  },
  {
    code: 'BH',
    nameAr: 'البحرين',
    nameEn: 'Bahrain',
    currency: 'BHD',
    currencyAr: 'دينار بحريني',
    currencySymbol: 'د.ب',
    currencyDecimals: 3,
    vatRate: 0.10,
    hasVat: true,
    fiscalYearStart: 'Jan',
    invoiceRequirements: {
      requiresQrCode: false,
      requiresTaxNumber: true,
      requiresCRNumber: true,
      requiresSequentialNumber: true,
      requiresBuyerDetails: false,
      digitalSignature: false,
      reportingToAuthority: false,
      retentionYears: 5,
    },
    taxAuthority: 'NBR — National Bureau for Revenue',
    taxAuthorityAr: 'الجهاز الوطني للإيرادات',
    complianceNotes: 'VAT 10%.',
    complianceNotesAr: 'ضريبة القيمة المضافة 10%.',
    phonePrefix: '+973',
    supportedPaymentMethods: ['benefit', 'visa', 'mastercard', 'cash', 'bank_transfer'],
  },
  {
    code: 'OM',
    nameAr: 'سلطنة عُمان',
    nameEn: 'Oman',
    currency: 'OMR',
    currencyAr: 'ريال عُماني',
    currencySymbol: 'ر.ع',
    currencyDecimals: 3,
    vatRate: 0.05,
    hasVat: true,
    fiscalYearStart: 'Jan',
    invoiceRequirements: {
      requiresQrCode: false,
      requiresTaxNumber: true,
      requiresCRNumber: true,
      requiresSequentialNumber: true,
      requiresBuyerDetails: false,
      digitalSignature: false,
      reportingToAuthority: false,
      retentionYears: 10,
    },
    taxAuthority: 'Tax Authority Oman',
    taxAuthorityAr: 'هيئة الضرائب العُمانية',
    complianceNotes: 'VAT 5%.',
    complianceNotesAr: 'ضريبة القيمة المضافة 5%.',
    phonePrefix: '+968',
    supportedPaymentMethods: ['visa', 'mastercard', 'cash', 'bank_transfer'],
  },
];

// ═══════════════════════════════════════════════════════════════════
// INDUSTRY TEMPLATES
// ═══════════════════════════════════════════════════════════════════

export const INDUSTRY_TEMPLATES: IndustryTemplate[] = [
  {
    id: 'tmpl-retail',
    type: 'retail',
    nameAr: 'تجزئة',
    nameEn: 'Retail',
    descriptionAr: 'متاجر البيع بالتجزئة والمحلات التجارية',
    descriptionEn: 'Retail stores and physical shops',
    icon: 'storefront',
    color: '#3B82F6',
    defaultChartOfAccountsKey: 'coa_retail',
    features: [
      { key: 'pos', nameAr: 'نقطة بيع', nameEn: 'POS Integration', enabled: true, required: false },
      { key: 'inventory', nameAr: 'إدارة المخزون', nameEn: 'Inventory Management', enabled: true, required: true },
      { key: 'barcode', nameAr: 'باركود', nameEn: 'Barcode Scanning', enabled: true, required: false },
    ],
    transactionRules: [
      { trigger: 'sale', debitAccount: '1100', creditAccount: '4000', nameAr: 'إيراد مبيعات', nameEn: 'Sales Revenue', autoPost: true },
      { trigger: 'sale', debitAccount: '5000', creditAccount: '1400', nameAr: 'تكلفة المبيعات', nameEn: 'COGS', autoPost: true },
    ],
    inventoryConfig: { trackInventory: true, valuationMethod: 'weighted_average', trackBatches: false, trackSerials: false, allowNegativeStock: false },
    reportingConfig: { primaryReports: ['sales', 'inventory', 'profit_loss'], dashboardKpis: ['sales', 'profit', 'inventory_value', 'receivables'], defaultPeriod: 'monthly' },
    dashboardWidgets: ['total_sales', 'net_profit', 'inventory_value', 'top_products', 'sales_chart'],
    recommendedModules: ['sales', 'inventory', 'customers', 'reports'],
  },
  {
    id: 'tmpl-perfume',
    type: 'perfume_trading',
    nameAr: 'تجارة العطور',
    nameEn: 'Perfume Trading',
    descriptionAr: 'محلات ومتاجر العطور والبخور والعود',
    descriptionEn: 'Perfumes, oud, and bakhoor trading',
    icon: 'local-florist',
    color: '#8B5CF6',
    defaultChartOfAccountsKey: 'coa_perfume',
    features: [
      { key: 'variants', nameAr: 'متغيرات المنتج', nameEn: 'Product Variants', enabled: true, required: true },
      { key: 'batch', nameAr: 'تتبع الدفعات', nameEn: 'Batch Tracking', enabled: true, required: false },
      { key: 'loyalty', nameAr: 'برنامج ولاء', nameEn: 'Loyalty Program', enabled: false, required: false },
    ],
    transactionRules: [
      { trigger: 'sale', debitAccount: '1100', creditAccount: '4000', nameAr: 'إيراد مبيعات', nameEn: 'Sales Revenue', autoPost: true },
      { trigger: 'sale', debitAccount: '5000', creditAccount: '1400', nameAr: 'تكلفة المبيعات', nameEn: 'COGS', autoPost: true },
    ],
    inventoryConfig: { trackInventory: true, valuationMethod: 'weighted_average', trackBatches: true, trackSerials: false, allowNegativeStock: false },
    reportingConfig: { primaryReports: ['sales', 'product_profitability', 'inventory'], dashboardKpis: ['sales', 'profit', 'top_products', 'inventory_value'], defaultPeriod: 'monthly' },
    dashboardWidgets: ['total_sales', 'gross_profit', 'top_products', 'low_stock_alert'],
    recommendedModules: ['sales', 'inventory', 'products', 'customers', 'reports'],
  },
  {
    id: 'tmpl-restaurant',
    type: 'restaurant',
    nameAr: 'مطاعم وكافيهات',
    nameEn: 'Restaurant & Café',
    descriptionAr: 'المطاعم والكافيهات وخدمات الطعام',
    descriptionEn: 'Restaurants, cafes, and food service',
    icon: 'restaurant',
    color: '#EF4444',
    defaultChartOfAccountsKey: 'coa_restaurant',
    features: [
      { key: 'table_management', nameAr: 'إدارة الطاولات', nameEn: 'Table Management', enabled: true, required: false },
      { key: 'kitchen_display', nameAr: 'شاشة المطبخ', nameEn: 'Kitchen Display', enabled: false, required: false },
    ],
    transactionRules: [
      { trigger: 'sale', debitAccount: '1100', creditAccount: '4000', nameAr: 'إيراد مبيعات', nameEn: 'Sales Revenue', autoPost: true },
    ],
    inventoryConfig: { trackInventory: true, valuationMethod: 'fifo', trackBatches: false, trackSerials: false, allowNegativeStock: false },
    reportingConfig: { primaryReports: ['daily_sales', 'expense_breakdown', 'food_cost'], dashboardKpis: ['daily_sales', 'food_cost_ratio', 'covers', 'avg_check'], defaultPeriod: 'daily' },
    dashboardWidgets: ['daily_sales', 'covers_count', 'avg_check', 'top_items'],
    recommendedModules: ['sales', 'expenses', 'inventory', 'reports'],
  },
  {
    id: 'tmpl-ecommerce',
    type: 'ecommerce',
    nameAr: 'تجارة إلكترونية',
    nameEn: 'E-Commerce',
    descriptionAr: 'المتاجر الإلكترونية وبيع عبر الإنترنت',
    descriptionEn: 'Online stores and e-commerce businesses',
    icon: 'shopping-bag',
    color: '#F59E0B',
    defaultChartOfAccountsKey: 'coa_ecommerce',
    features: [
      { key: 'api_sync', nameAr: 'مزامنة API', nameEn: 'API Sync', enabled: true, required: true },
      { key: 'multi_warehouse', nameAr: 'مستودعات متعددة', nameEn: 'Multi-Warehouse', enabled: true, required: false },
    ],
    transactionRules: [
      { trigger: 'sale', debitAccount: '1100', creditAccount: '4000', nameAr: 'إيراد مبيعات', nameEn: 'Sales Revenue', autoPost: true },
      { trigger: 'sale', debitAccount: '5000', creditAccount: '1400', nameAr: 'تكلفة المبيعات', nameEn: 'COGS', autoPost: true },
    ],
    inventoryConfig: { trackInventory: true, valuationMethod: 'weighted_average', trackBatches: false, trackSerials: false, allowNegativeStock: false },
    reportingConfig: { primaryReports: ['channel_sales', 'returns', 'fulfillment'], dashboardKpis: ['orders', 'revenue', 'returns_rate', 'avg_order'], defaultPeriod: 'daily' },
    dashboardWidgets: ['orders_today', 'revenue', 'conversion_rate', 'returns'],
    recommendedModules: ['sales', 'inventory', 'customers', 'integrations', 'reports'],
  },
  {
    id: 'tmpl-services',
    type: 'services',
    nameAr: 'خدمات',
    nameEn: 'Services',
    descriptionAr: 'شركات الخدمات غير المخزونية',
    descriptionEn: 'Service-based businesses without inventory',
    icon: 'miscellaneous-services',
    color: '#10B981',
    defaultChartOfAccountsKey: 'coa_services',
    features: [
      { key: 'time_tracking', nameAr: 'تتبع الوقت', nameEn: 'Time Tracking', enabled: false, required: false },
      { key: 'project', nameAr: 'إدارة المشاريع', nameEn: 'Project Management', enabled: false, required: false },
    ],
    transactionRules: [
      { trigger: 'sale', debitAccount: '1100', creditAccount: '4100', nameAr: 'إيراد خدمات', nameEn: 'Service Revenue', autoPost: true },
    ],
    inventoryConfig: { trackInventory: false, valuationMethod: 'weighted_average', trackBatches: false, trackSerials: false, allowNegativeStock: false },
    reportingConfig: { primaryReports: ['revenue_by_service', 'expense_breakdown', 'receivables'], dashboardKpis: ['monthly_revenue', 'outstanding', 'expenses', 'net_profit'], defaultPeriod: 'monthly' },
    dashboardWidgets: ['monthly_revenue', 'receivables', 'expenses', 'net_profit'],
    recommendedModules: ['sales', 'customers', 'expenses', 'reports'],
  },
  {
    id: 'tmpl-contracting',
    type: 'contracting',
    nameAr: 'مقاولات',
    nameEn: 'Contracting',
    descriptionAr: 'شركات المقاولات والإنشاء',
    descriptionEn: 'Construction and contracting companies',
    icon: 'construction',
    color: '#64748B',
    defaultChartOfAccountsKey: 'coa_contracting',
    features: [
      { key: 'project_costing', nameAr: 'تكاليف المشاريع', nameEn: 'Project Costing', enabled: true, required: true },
      { key: 'retention', nameAr: 'محاسبة الاستقطاعات', nameEn: 'Retention Accounting', enabled: true, required: false },
    ],
    transactionRules: [
      { trigger: 'sale', debitAccount: '1100', creditAccount: '4000', nameAr: 'إيراد عقود', nameEn: 'Contract Revenue', autoPost: true },
    ],
    inventoryConfig: { trackInventory: true, valuationMethod: 'specific_identification', trackBatches: false, trackSerials: false, allowNegativeStock: false },
    reportingConfig: { primaryReports: ['project_profitability', 'cash_flow', 'balance_sheet'], dashboardKpis: ['active_contracts', 'billings', 'receivables', 'cost_to_complete'], defaultPeriod: 'monthly' },
    dashboardWidgets: ['active_projects', 'total_billings', 'receivables', 'project_margin'],
    recommendedModules: ['sales', 'purchases', 'expenses', 'accounting', 'reports'],
  },
];

// ═══════════════════════════════════════════════════════════════════
// BILLING PLANS
// ═══════════════════════════════════════════════════════════════════

export const BILLING_PLANS: PlanConfig[] = [
  {
    plan: 'starter',
    nameAr: 'الأساسي',
    nameEn: 'Starter',
    descriptionAr: 'للشركات الناشئة والصغيرة',
    descriptionEn: 'For startups and small businesses',
    icon: 'rocket-launch',
    color: '#64748B',
    features: [
      { key: 'companies', nameAr: 'شركة واحدة', nameEn: '1 Company', included: true },
      { key: 'users', nameAr: 'حتى 3 مستخدمين', nameEn: 'Up to 3 users', included: true },
      { key: 'branches', nameAr: 'فرع واحد', nameEn: '1 Branch', included: true },
      { key: 'sales_purchases', nameAr: 'مبيعات ومشتريات', nameEn: 'Sales & Purchases', included: true },
      { key: 'inventory', nameAr: 'إدارة المخزون', nameEn: 'Inventory', included: true },
      { key: 'reports', nameAr: 'تقارير أساسية', nameEn: 'Basic Reports', included: true },
      { key: 'api', nameAr: 'API', nameEn: 'API Access', included: false },
      { key: 'embedded', nameAr: 'Embedded Mode', nameEn: 'Embedded Mode', included: false },
      { key: 'white_label', nameAr: 'White Label', nameEn: 'White Label', included: false },
      { key: 'ai', nameAr: 'ذكاء اصطناعي', nameEn: 'AI Insights', included: false },
    ],
    limits: {
      companies: 1, users: 3, branches: 1,
      api_calls_per_month: 0, storage_gb: 5, webhooks: 0,
      white_label: false, embedded_mode: false, sandbox: false,
      developer_portal: false, ai_insights: false, multi_currency: false,
      advanced_reports: false, api_access: false, dedicated_support: false,
    },
  },
  {
    plan: 'business',
    nameAr: 'الأعمال',
    nameEn: 'Business',
    descriptionAr: 'للشركات المتنامية',
    descriptionEn: 'For growing businesses',
    icon: 'business-center',
    color: '#3B82F6',
    isPopular: true,
    features: [
      { key: 'companies', nameAr: 'حتى 5 شركات', nameEn: 'Up to 5 companies', included: true, highlight: true },
      { key: 'users', nameAr: 'حتى 25 مستخدم', nameEn: 'Up to 25 users', included: true },
      { key: 'branches', nameAr: 'فروع غير محدودة', nameEn: 'Unlimited branches', included: true, highlight: true },
      { key: 'api', nameAr: 'API (50K طلب/شهر)', nameEn: 'API (50K req/month)', included: true, highlight: true },
      { key: 'webhooks', nameAr: 'Webhooks', nameEn: 'Webhooks', included: true },
      { key: 'ai', nameAr: 'ذكاء مالي', nameEn: 'AI Financial Intelligence', included: true, highlight: true },
      { key: 'advanced_reports', nameAr: 'تقارير متقدمة', nameEn: 'Advanced Reports', included: true },
      { key: 'multi_currency', nameAr: 'عملات متعددة', nameEn: 'Multi-Currency', included: true },
      { key: 'embedded', nameAr: 'Embedded Mode', nameEn: 'Embedded Mode', included: false },
      { key: 'white_label', nameAr: 'White Label', nameEn: 'White Label', included: false },
    ],
    limits: {
      companies: 5, users: 25, branches: 'unlimited',
      api_calls_per_month: 50000, storage_gb: 50, webhooks: 10,
      white_label: false, embedded_mode: false, sandbox: true,
      developer_portal: true, ai_insights: true, multi_currency: true,
      advanced_reports: true, api_access: true, dedicated_support: false,
    },
  },
  {
    plan: 'enterprise',
    nameAr: 'المؤسسات',
    nameEn: 'Enterprise',
    descriptionAr: 'للمؤسسات الكبيرة',
    descriptionEn: 'For large enterprises',
    icon: 'corporate-fare',
    color: '#8B5CF6',
    isEnterprise: true,
    features: [
      { key: 'companies', nameAr: 'شركات غير محدودة', nameEn: 'Unlimited companies', included: true, highlight: true },
      { key: 'users', nameAr: 'مستخدمون غير محدودون', nameEn: 'Unlimited users', included: true, highlight: true },
      { key: 'api', nameAr: 'API غير محدود', nameEn: 'Unlimited API', included: true, highlight: true },
      { key: 'embedded', nameAr: 'Embedded Mode', nameEn: 'Embedded Mode', included: true, highlight: true },
      { key: 'white_label', nameAr: 'White Label', nameEn: 'White Label', included: true, highlight: true },
      { key: 'sla', nameAr: 'SLA مضمون', nameEn: 'Guaranteed SLA', included: true },
      { key: 'dedicated', nameAr: 'دعم مخصص', nameEn: 'Dedicated Support', included: true, highlight: true },
      { key: 'custom', nameAr: 'تطوير مخصص', nameEn: 'Custom Development', included: true },
    ],
    limits: {
      companies: 'unlimited', users: 'unlimited', branches: 'unlimited',
      api_calls_per_month: 'unlimited', storage_gb: 'unlimited', webhooks: 'unlimited',
      white_label: true, embedded_mode: true, sandbox: true,
      developer_portal: true, ai_insights: true, multi_currency: true,
      advanced_reports: true, api_access: true, dedicated_support: true,
    },
  },
  {
    plan: 'api_plan',
    nameAr: 'API',
    nameEn: 'API Plan',
    descriptionAr: 'للمطورين وشركات التقنية',
    descriptionEn: 'For developers and tech companies',
    icon: 'code',
    color: '#10B981',
    features: [
      { key: 'api', nameAr: 'API أولاً', nameEn: 'API-first Access', included: true, highlight: true },
      { key: 'sandbox', nameAr: 'Sandbox بيئة', nameEn: 'Full Sandbox', included: true, highlight: true },
      { key: 'webhooks', nameAr: 'Webhooks غير محدودة', nameEn: 'Unlimited Webhooks', included: true },
      { key: 'developer_portal', nameAr: 'Developer Portal', nameEn: 'Developer Portal', included: true, highlight: true },
      { key: 'docs', nameAr: 'توثيق شامل', nameEn: 'Full API Documentation', included: true },
    ],
    limits: {
      companies: 3, users: 10, branches: 'unlimited',
      api_calls_per_month: 'unlimited', storage_gb: 20, webhooks: 'unlimited',
      white_label: false, embedded_mode: true, sandbox: true,
      developer_portal: true, ai_insights: true, multi_currency: true,
      advanced_reports: true, api_access: true, dedicated_support: false,
    },
  },
];

// ═══════════════════════════════════════════════════════════════════
// DEMO: FINANCIAL HEALTH SCORE
// ═══════════════════════════════════════════════════════════════════

export const DEMO_FINANCIAL_HEALTH: FinancialHealthScore = {
  company_id: 'company-001',
  overall_score: 74,
  level: 'good',
  calculated_at: '2024-06-30T00:00:00Z',
  trend: 'improving',
  trend_change: 6,
  metrics: [
    { key: 'profitability', nameAr: 'الربحية', nameEn: 'Profitability', score: 82, weight: 0.25, value: '18.4%', benchmark: '15%', status: 'good', descriptionAr: 'هامش ربح صافي قوي فوق المعدل', descriptionEn: 'Strong net profit margin above benchmark' },
    { key: 'cash_flow', nameAr: 'التدفق النقدي', nameEn: 'Cash Flow', score: 68, weight: 0.25, value: '12,450 KWD', benchmark: '15,000 KWD', status: 'fair', descriptionAr: 'التدفق النقدي أقل من المستهدف قليلاً', descriptionEn: 'Cash flow slightly below target' },
    { key: 'receivables', nameAr: 'الذمم المدينة', nameEn: 'Receivables', score: 60, weight: 0.20, value: '45 days', benchmark: '30 days', status: 'fair', descriptionAr: 'متوسط التحصيل أعلى من المعيار', descriptionEn: 'Collection period above benchmark' },
    { key: 'liquidity', nameAr: 'السيولة', nameEn: 'Liquidity', score: 88, weight: 0.15, value: '2.4x', benchmark: '1.5x', status: 'excellent', descriptionAr: 'نسبة سيولة ممتازة', descriptionEn: 'Excellent liquidity ratio' },
    { key: 'expenses', nameAr: 'المصروفات', nameEn: 'Expenses', score: 70, weight: 0.15, value: '68%', benchmark: '65%', status: 'fair', descriptionAr: 'نسبة المصروفات أعلى قليلاً من المثالي', descriptionEn: 'Expense ratio slightly above ideal' },
  ],
  insights: [
    { type: 'recommendation', priority: 'high', titleAr: 'تسريع التحصيل', titleEn: 'Speed Up Collections', descriptionAr: 'لديك 15,200 د.ك ذمم مستحقة منذ أكثر من 60 يوم', descriptionEn: 'You have KWD 15,200 in receivables overdue 60+ days', metric: 'receivables', actionAr: 'مراجعة الذمم المتأخرة', actionEn: 'Review aging receivables', icon: 'warning', color: '#F59E0B' },
    { type: 'positive', priority: 'low', titleAr: 'هامش ربح قوي', titleEn: 'Strong Profit Margin', descriptionAr: 'هامش الربح الصافي 18.4% أعلى من معدل الصناعة', descriptionEn: 'Net profit margin 18.4% exceeds industry average', metric: 'profitability', icon: 'trending-up', color: '#10B981' },
    { type: 'alert', priority: 'medium', titleAr: 'ارتفاع في المصروفات', titleEn: 'Expense Increase', descriptionAr: 'ارتفعت المصروفات التشغيلية 8% هذا الشهر', descriptionEn: 'Operating expenses up 8% this month', metric: 'expenses', actionAr: 'مراجعة تفاصيل المصروفات', actionEn: 'Review expense breakdown', icon: 'receipt-long', color: '#EF4444' },
  ],
};

// ═══════════════════════════════════════════════════════════════════
// DEMO: BUSINESS INSIGHTS
// ═══════════════════════════════════════════════════════════════════

export const DEMO_INSIGHTS: BusinessInsight[] = [
  {
    id: 'ins-001', company_id: 'company-001', type: 'sales_increase', priority: 'positive',
    titleAr: 'ارتفاع في المبيعات', titleEn: 'Sales Increase',
    descriptionAr: 'المبيعات ارتفعت 12% مقارنة بالشهر الماضي', descriptionEn: 'Sales are up 12% compared to last month',
    metric: 'total_sales', current_value: 45230, previous_value: 40380, change_percent: 12,
    is_positive: true, icon: 'trending-up', color: '#10B981',
    actionAr: 'عرض تفاصيل المبيعات', actionEn: 'View sales details',
    dismissed: false, generated_at: '2024-06-30T06:00:00Z',
  },
  {
    id: 'ins-002', company_id: 'company-001', type: 'expense_spike', priority: 'medium',
    titleAr: 'ارتفاع المصروفات', titleEn: 'Expense Spike',
    descriptionAr: 'المصروفات ارتفعت 18% — تحقق من مصروفات التشغيل', descriptionEn: 'Expenses up 18% — check operating costs',
    metric: 'total_expenses', current_value: 28400, previous_value: 24068, change_percent: 18,
    is_positive: false, icon: 'receipt-long', color: '#F59E0B',
    actionAr: 'مراجعة المصروفات', actionEn: 'Review expenses',
    dismissed: false, generated_at: '2024-06-30T06:00:00Z',
  },
  {
    id: 'ins-003', company_id: 'company-001', type: 'receivables_overdue', priority: 'high',
    titleAr: 'ذمم متأخرة', titleEn: 'Overdue Receivables',
    descriptionAr: 'لديك 15,200 د.ك ذمم مستحقة منذ أكثر من 30 يوم', descriptionEn: 'KWD 15,200 in receivables overdue 30+ days',
    metric: 'overdue_receivables', current_value: 15200, is_positive: false,
    icon: 'people', color: '#EF4444',
    actionAr: 'مراجعة العملاء المتأخرين', actionEn: 'Review overdue customers',
    dismissed: false, generated_at: '2024-06-30T06:00:00Z',
  },
  {
    id: 'ins-004', company_id: 'company-001', type: 'inventory_low', priority: 'high',
    titleAr: 'تنبيه مخزون', titleEn: 'Stock Alert',
    descriptionAr: '5 منتجات وصلت لحد إعادة الطلب أو نفدت', descriptionEn: '5 products reached reorder point or are out of stock',
    metric: 'low_stock_count', current_value: 5, is_positive: false,
    icon: 'inventory', color: '#EF4444',
    actionAr: 'مراجعة المخزون', actionEn: 'Review inventory',
    dismissed: false, generated_at: '2024-06-30T06:00:00Z',
  },
  {
    id: 'ins-005', company_id: 'company-001', type: 'top_product', priority: 'positive',
    titleAr: 'أعلى مبيع', titleEn: 'Top Seller',
    descriptionAr: 'عود ملكي فاخر هو الأكثر مبيعًا هذا الشهر بإيراد 11,250 د.ك', descriptionEn: 'Royal Oud Premium is the top seller this month with KWD 11,250 revenue',
    metric: 'top_product', current_value: 'Royal Oud Premium', is_positive: true,
    icon: 'star', color: '#8B5CF6',
    dismissed: false, generated_at: '2024-06-30T06:00:00Z',
  },
];

// ═══════════════════════════════════════════════════════════════════
// DEMO: API KEYS
// ═══════════════════════════════════════════════════════════════════

export const DEMO_API_KEYS: ApiKey[] = [
  {
    id: 'key-001', company_id: 'company-001',
    name: 'Main App Integration',
    nameAr: 'تكامل التطبيق الرئيسي',
    key_prefix: 'live_k8xP',
    key_hash: 'hashed_key_001',
    type: 'live', status: 'active',
    permissions: ['sales:read', 'sales:write', 'customers:read', 'customers:write', 'products:read', 'inventory:read'],
    rate_limit: 1000,
    last_used_at: '2024-06-30T10:30:00Z',
    created_by: 'user-002',
    created_at: '2024-01-15T00:00:00Z',
  },
  {
    id: 'key-002', company_id: 'company-001',
    name: 'Sandbox Testing',
    nameAr: 'اختبار Sandbox',
    key_prefix: 'test_m3qW',
    key_hash: 'hashed_key_002',
    type: 'sandbox', status: 'active',
    permissions: ['sales:read', 'sales:write', 'customers:read', 'customers:write', 'products:read', 'products:write', 'inventory:read', 'inventory:write', 'reports:read'],
    rate_limit: 100,
    last_used_at: '2024-06-28T14:00:00Z',
    created_by: 'user-002',
    created_at: '2024-03-01T00:00:00Z',
  },
];

// ═══════════════════════════════════════════════════════════════════
// DEMO: WEBHOOKS
// ═══════════════════════════════════════════════════════════════════

export const DEMO_WEBHOOKS: Webhook[] = [
  {
    id: 'wh-001', company_id: 'company-001',
    name: 'Main App Sales Webhook',
    url: 'https://myapp.example.com/webhooks/accounting',
    secret: 'whsec_****',
    events: ['sale.created', 'sale.paid', 'payment.created', 'invoice.paid'],
    status: 'active',
    failure_count: 0,
    last_triggered_at: '2024-06-30T10:30:00Z',
    last_success_at: '2024-06-30T10:30:00Z',
    created_by: 'user-002',
    created_at: '2024-01-15T00:00:00Z',
  },
  {
    id: 'wh-002', company_id: 'company-001',
    name: 'Inventory Low Stock Alert',
    url: 'https://myapp.example.com/webhooks/inventory',
    secret: 'whsec_****',
    events: ['inventory.low_stock', 'inventory.out_of_stock'],
    status: 'active',
    failure_count: 0,
    last_triggered_at: '2024-06-26T08:00:00Z',
    last_success_at: '2024-06-26T08:00:00Z',
    created_by: 'user-002',
    created_at: '2024-02-01T00:00:00Z',
  },
  {
    id: 'wh-003', company_id: 'company-001',
    name: 'Expense Approvals',
    url: 'https://myapp.example.com/webhooks/expenses',
    secret: 'whsec_****',
    events: ['expense.created', 'expense.approved', 'expense.rejected'],
    status: 'failing',
    failure_count: 3,
    last_triggered_at: '2024-06-25T12:00:00Z',
    last_failure_at: '2024-06-25T12:00:00Z',
    last_failure_message: 'Connection timeout',
    created_by: 'user-002',
    created_at: '2024-04-01T00:00:00Z',
  },
];

// ═══════════════════════════════════════════════════════════════════
// DEMO: SANDBOX
// ═══════════════════════════════════════════════════════════════════

export const DEMO_SANDBOX: SandboxEnvironment = {
  id: 'sandbox-001',
  company_id: 'company-001',
  name: 'Development Sandbox',
  status: 'active',
  data_seeded: true,
  seed_template: 'perfume_trading',
  api_key_sandbox: 'test_m3qW****',
  created_at: '2024-03-01T00:00:00Z',
  last_reset_at: '2024-06-01T00:00:00Z',
};
