// Sales Module — Demo Data
// DEMO DATA FOR DEVELOPMENT — Replace with real API calls

import {
  SaleInvoiceFull, SalesDashboardStats, SalesPolicy, SalesAccountingMapping,
  SalePaymentRecord, CreditNote, SalesReturn, Quotation,
  SALE_STATUS_CONFIG,
} from '../types/sales';
import { ProductFull, Warehouse, StockLevel } from '../types/inventory';
import { CustomerFull } from '../types/customers';

// ═══════════════════════════════════════════════════════════════════
// SALES POLICY (Company Defaults)
// ═══════════════════════════════════════════════════════════════════

export const DEMO_SALES_POLICY: SalesPolicy = {
  company_id: 'company-001',
  target_gross_margin: 0.30,          // 30%
  below_margin_action: 'warn',
  negative_margin_action: 'require_approval',
  allow_negative_stock: false,
  negative_stock_action: 'warn',
  credit_limit_action: 'warn',
  max_line_discount_percent: 30,
  max_invoice_discount_percent: 20,
  require_approval_above_discount: 15,
  invoice_prefix: 'INV',
  invoice_next_number: 1089,
  use_branch_prefix: false,
  reset_numbering_yearly: true,
  require_quotation: false,
  require_sales_order: false,
  require_approval_before_invoice: false,
  allow_partial_payment: true,
  show_cost_to_salesperson: false,
  show_margin_to_salesperson: false,
  include_payment_fee_in_profitability: true,
  include_delivery_in_profitability: true,
  include_marketing_allocation: false,
  monthly_marketing_budget: 500,
};

// ═══════════════════════════════════════════════════════════════════
// ACCOUNTING MAPPING
// ═══════════════════════════════════════════════════════════════════

export const DEMO_ACCOUNTING_MAPPING: SalesAccountingMapping = {
  company_id: 'company-001',
  cash_sales_account: '1100',
  credit_sales_account: '1200',
  revenue_account: '4000',
  returns_account: '4100',
  discount_account: '4200',
  inventory_account: '1400',
  cogs_account: '5000',
  tax_payable_account: '2100',
  payment_fee_account: '6100',
};

// ═══════════════════════════════════════════════════════════════════
// DEMO PRODUCTS (for invoice creation)
// ═══════════════════════════════════════════════════════════════════

export const DEMO_SALE_PRODUCTS: (ProductFull & { current_stock: number; warehouse_stock: Record<string, number> })[] = [
  {
    id: 'prod-001',
    company_id: 'company-001',
    category_id: 'cat-001',
    brand_id: 'brand-001',
    sku: 'OUD-001',
    barcode: '6281234000001',
    name: 'Royal Oud Premium',
    name_ar: 'عود ملكي فاخر',
    description: 'Premium aged oud from Assam',
    description_ar: 'عود معتق فاخر من أسام',
    type: 'product',
    unit_id: 'unit-001',
    unit_symbol: 'PCS',
    cost_price: 45.000,
    sale_price: 75.000,
    purchase_price: 45.000,
    tax_rate: 0,
    tax_included: false,
    track_inventory: true,
    tracking_type: 'batch',
    costing_method: 'weighted_average',
    min_stock: 5,
    max_stock: 200,
    reorder_point: 15,
    status: 'active',
    is_active: true,
    has_variants: false,
    created_by: 'user-002',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-06-01T00:00:00Z',
    current_stock: 87,
    stock_value: 3915,
    warehouse_stock: { 'wh-001': 60, 'wh-002': 27 },
  },
  {
    id: 'prod-002',
    company_id: 'company-001',
    category_id: 'cat-002',
    brand_id: 'brand-002',
    sku: 'PERF-001',
    barcode: '6281234000002',
    name: 'Desert Rose EDP 100ml',
    name_ar: 'وردة الصحراء عطر 100مل',
    type: 'product',
    unit_id: 'unit-006',
    unit_symbol: 'ML',
    cost_price: 18.500,
    sale_price: 35.000,
    purchase_price: 18.500,
    tax_rate: 0,
    tax_included: false,
    track_inventory: true,
    tracking_type: 'none',
    costing_method: 'weighted_average',
    min_stock: 10,
    max_stock: 500,
    reorder_point: 30,
    status: 'active',
    is_active: true,
    has_variants: true,
    created_by: 'user-002',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-06-01T00:00:00Z',
    current_stock: 142,
    stock_value: 2627,
    warehouse_stock: { 'wh-001': 100, 'wh-002': 42 },
  },
  {
    id: 'prod-003',
    company_id: 'company-001',
    category_id: 'cat-001',
    brand_id: 'brand-001',
    sku: 'BKH-001',
    barcode: '6281234000003',
    name: 'Bakhoor Al-Malak',
    name_ar: 'بخور الملاك',
    type: 'product',
    unit_id: 'unit-001',
    unit_symbol: 'PCS',
    cost_price: 8.250,
    sale_price: 18.000,
    purchase_price: 8.250,
    tax_rate: 0,
    tax_included: false,
    track_inventory: true,
    tracking_type: 'none',
    costing_method: 'weighted_average',
    min_stock: 20,
    max_stock: 500,
    reorder_point: 50,
    status: 'active',
    is_active: true,
    has_variants: false,
    created_by: 'user-002',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-06-01T00:00:00Z',
    current_stock: 234,
    stock_value: 1930.5,
    warehouse_stock: { 'wh-001': 180, 'wh-002': 54 },
  },
  {
    id: 'prod-004',
    company_id: 'company-001',
    category_id: 'cat-002',
    brand_id: 'brand-003',
    sku: 'PERF-002',
    barcode: '6281234000004',
    name: 'Amber Musk 50ml',
    name_ar: 'عنبر المسك 50مل',
    type: 'product',
    unit_id: 'unit-006',
    unit_symbol: 'ML',
    cost_price: 12.000,
    sale_price: 22.000,
    purchase_price: 12.000,
    tax_rate: 0,
    tax_included: false,
    track_inventory: true,
    tracking_type: 'none',
    costing_method: 'weighted_average',
    min_stock: 15,
    max_stock: 300,
    reorder_point: 30,
    status: 'active',
    is_active: true,
    has_variants: false,
    created_by: 'user-002',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-06-01T00:00:00Z',
    current_stock: 8,
    stock_value: 96,
    warehouse_stock: { 'wh-001': 8, 'wh-002': 0 },
  },
  {
    id: 'prod-005',
    company_id: 'company-001',
    category_id: 'cat-003',
    brand_id: 'brand-001',
    sku: 'OIL-001',
    barcode: '6281234000005',
    name: 'Oud Oil Pure 3ml',
    name_ar: 'زيت عود أصيل 3مل',
    type: 'product',
    unit_id: 'unit-006',
    unit_symbol: 'ML',
    cost_price: 95.000,
    sale_price: 150.000,
    purchase_price: 95.000,
    tax_rate: 0,
    tax_included: false,
    track_inventory: true,
    tracking_type: 'batch',
    costing_method: 'weighted_average',
    min_stock: 5,
    max_stock: 50,
    reorder_point: 10,
    status: 'active',
    is_active: true,
    has_variants: false,
    created_by: 'user-002',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-06-01T00:00:00Z',
    current_stock: 0,
    stock_value: 0,
    warehouse_stock: { 'wh-001': 0, 'wh-002': 0 },
  },
];

// ═══════════════════════════════════════════════════════════════════
// DEMO CUSTOMERS (for invoice selection)
// ═══════════════════════════════════════════════════════════════════

export const DEMO_SALE_CUSTOMERS: Partial<CustomerFull>[] = [
  { id: 'cust-001', name: 'Ahmad Mohammed Al-Rashidi', name_ar: 'أحمد محمد الراشدي', code: 'C-0001', phone: '+965 9901 0001', type: 'individual', status: 'active', credit_limit: 2000, balance: 450.500, payment_terms: '30_days' },
  { id: 'cust-002', name: 'Kuwait Gift Trading Co.', name_ar: 'شركة الكويت للهدايا', code: 'C-0002', phone: '+965 2234 5678', type: 'company', status: 'active', credit_limit: 10000, balance: 3200.000, payment_terms: '30_days' },
  { id: 'cust-003', name: 'Fatima Al-Sabah', name_ar: 'فاطمة الصباح', code: 'C-0003', phone: '+965 9902 0002', type: 'individual', status: 'active', credit_limit: 500, balance: 0, payment_terms: 'cash' },
  { id: 'cust-004', name: 'Al-Nakheel Perfumes LLC', name_ar: 'شركة النخيل للعطور', code: 'C-0004', phone: '+965 2245 6789', type: 'company', status: 'active', credit_limit: 25000, balance: 8750.000, payment_terms: '60_days' },
  { id: 'cust-005', name: 'Mohammed Khalid Al-Mutairi', name_ar: 'محمد خالد المطيري', code: 'C-0005', phone: '+965 9903 0003', type: 'individual', status: 'active', credit_limit: 1000, balance: 175.500, payment_terms: '15_days' },
];

// ═══════════════════════════════════════════════════════════════════
// DEMO WAREHOUSES
// ═══════════════════════════════════════════════════════════════════

export const DEMO_SALE_WAREHOUSES: Partial<Warehouse>[] = [
  { id: 'wh-001', name: 'Main Warehouse', name_ar: 'المستودع الرئيسي', code: 'WH-MAIN', is_default: true },
  { id: 'wh-002', name: 'Salmiya Store', name_ar: 'مستودع السالمية', code: 'WH-SLM', is_default: false },
];

// ═══════════════════════════════════════════════════════════════════
// DEMO INVOICES
// ═══════════════════════════════════════════════════════════════════

export const DEMO_INVOICES: SaleInvoiceFull[] = [
  {
    id: 'inv-001',
    company_id: 'company-001',
    branch_id: 'branch-001',
    invoice_number: 'INV-2026-001074',
    customer_id: 'cust-002',
    customer_name: 'Kuwait Gift Trading Co.',
    customer_name_ar: 'شركة الكويت للهدايا',
    customer_code: 'C-0002',
    date: '2026-08-28',
    due_date: '2026-09-27',
    channel: 'manual',
    salesperson_id: 'user-004',
    salesperson_name: 'Khalid Al-Mutairi',
    warehouse_id: 'wh-001',
    warehouse_name: 'Main Warehouse',
    items: [
      {
        id: 'item-001-1',
        invoice_id: 'inv-001',
        line_number: 1,
        product_id: 'prod-001',
        product_name: 'Royal Oud Premium',
        product_name_ar: 'عود ملكي فاخر',
        product_code: 'OUD-001',
        quantity: 5,
        unit_id: 'unit-001',
        unit_symbol: 'PCS',
        unit_price: 75.000,
        line_discount_type: 'percentage',
        line_discount_value: 5,
        line_discount_amount: 18.750,
        line_subtotal: 356.250,
        tax_rate: 0,
        tax_amount: 0,
        line_total: 356.250,
        unit_cost: 45.000,
        total_cost: 225.000,
        gross_profit: 131.250,
        gross_margin_percent: 36.84,
        allocated_payment_fee: 0,
        allocated_delivery_cost: 0,
        allocated_marketing_cost: 0,
        allocated_other_costs: 0,
        total_commercial_costs: 0,
        commercial_profit: 131.250,
        commercial_margin_percent: 36.84,
        is_below_target_margin: false,
        is_negative_margin: false,
        warehouse_id: 'wh-001',
        available_stock: 60,
        stock_sufficient: true,
      },
      {
        id: 'item-001-2',
        invoice_id: 'inv-001',
        line_number: 2,
        product_id: 'prod-003',
        product_name: 'Bakhoor Al-Malak',
        product_name_ar: 'بخور الملاك',
        product_code: 'BKH-001',
        quantity: 10,
        unit_id: 'unit-001',
        unit_symbol: 'PCS',
        unit_price: 18.000,
        line_discount_type: 'percentage',
        line_discount_value: 0,
        line_discount_amount: 0,
        line_subtotal: 180.000,
        tax_rate: 0,
        tax_amount: 0,
        line_total: 180.000,
        unit_cost: 8.250,
        total_cost: 82.500,
        gross_profit: 97.500,
        gross_margin_percent: 54.17,
        allocated_payment_fee: 0,
        allocated_delivery_cost: 0,
        allocated_marketing_cost: 0,
        allocated_other_costs: 0,
        total_commercial_costs: 0,
        commercial_profit: 97.500,
        commercial_margin_percent: 54.17,
        is_below_target_margin: false,
        is_negative_margin: false,
        warehouse_id: 'wh-001',
        available_stock: 180,
        stock_sufficient: true,
      },
    ],
    subtotal: 536.250,
    invoice_discount_type: 'percentage',
    invoice_discount_value: 0,
    invoice_discount_amount: 0,
    tax_amount: 0,
    total: 536.250,
    paid_amount: 0,
    outstanding: 536.250,
    payments: [],
    payment_method: 'credit',
    payment_fee: 0,
    status: 'approved',
    profitability: {
      invoice_id: 'inv-001',
      revenue: 536.250,
      accounting_cogs: 307.500,
      gross_profit: 228.750,
      gross_margin_percent: 42.65,
      payment_fee: 0,
      delivery_cost: 0,
      marketing_cost_allocation: 0,
      other_costs: 0,
      total_commercial_costs: 0,
      commercial_profit: 228.750,
      commercial_margin_percent: 42.65,
      line_profitability: [],
    },
    accounting_status: 'posted',
    created_by: 'user-004',
    created_at: '2026-08-28T09:00:00Z',
    updated_at: '2026-08-28T09:00:00Z',
  },
  {
    id: 'inv-002',
    company_id: 'company-001',
    branch_id: 'branch-002',
    invoice_number: 'INV-2026-001075',
    customer_id: 'cust-001',
    customer_name: 'Ahmad Mohammed Al-Rashidi',
    customer_name_ar: 'أحمد محمد الراشدي',
    customer_code: 'C-0001',
    date: '2026-08-29',
    due_date: '2026-09-28',
    channel: 'pos',
    salesperson_id: 'user-004',
    salesperson_name: 'Khalid Al-Mutairi',
    warehouse_id: 'wh-002',
    warehouse_name: 'Salmiya Store',
    items: [
      {
        id: 'item-002-1',
        invoice_id: 'inv-002',
        line_number: 1,
        product_id: 'prod-002',
        product_name: 'Desert Rose EDP 100ml',
        product_name_ar: 'وردة الصحراء عطر 100مل',
        product_code: 'PERF-001',
        quantity: 2,
        unit_id: 'unit-006',
        unit_symbol: 'ML',
        unit_price: 35.000,
        line_discount_type: 'percentage',
        line_discount_value: 0,
        line_discount_amount: 0,
        line_subtotal: 70.000,
        tax_rate: 0,
        tax_amount: 0,
        line_total: 70.000,
        unit_cost: 18.500,
        total_cost: 37.000,
        gross_profit: 33.000,
        gross_margin_percent: 47.14,
        allocated_payment_fee: 1.400,
        allocated_delivery_cost: 0,
        allocated_marketing_cost: 0,
        allocated_other_costs: 0,
        total_commercial_costs: 1.400,
        commercial_profit: 31.600,
        commercial_margin_percent: 45.14,
        is_below_target_margin: false,
        is_negative_margin: false,
        warehouse_id: 'wh-002',
        available_stock: 42,
        stock_sufficient: true,
      },
    ],
    subtotal: 70.000,
    invoice_discount_type: 'percentage',
    invoice_discount_value: 0,
    invoice_discount_amount: 0,
    tax_amount: 0,
    total: 70.000,
    paid_amount: 70.000,
    outstanding: 0,
    payments: [
      {
        id: 'pay-002-1', invoice_id: 'inv-002', company_id: 'company-001',
        payment_number: 'PAY-2026-000087', date: '2026-08-29', amount: 70.000,
        method: 'card', reference: 'CARD-TXN-98721', is_reversed: false,
        created_by: 'user-004', created_at: '2026-08-29T11:30:00Z',
      },
    ],
    payment_method: 'card',
    payment_fee: 1.400,
    payment_fee_rate: 0.02,
    status: 'paid',
    profitability: {
      invoice_id: 'inv-002',
      revenue: 70.000,
      accounting_cogs: 37.000,
      gross_profit: 33.000,
      gross_margin_percent: 47.14,
      payment_fee: 1.400,
      delivery_cost: 0,
      marketing_cost_allocation: 0,
      other_costs: 0,
      total_commercial_costs: 1.400,
      commercial_profit: 31.600,
      commercial_margin_percent: 45.14,
      line_profitability: [],
    },
    accounting_status: 'posted',
    created_by: 'user-004',
    created_at: '2026-08-29T11:00:00Z',
    updated_at: '2026-08-29T11:30:00Z',
  },
  {
    id: 'inv-003',
    company_id: 'company-001',
    branch_id: 'branch-001',
    invoice_number: 'INV-2026-001076',
    customer_id: 'cust-004',
    customer_name: 'Al-Nakheel Perfumes LLC',
    customer_name_ar: 'شركة النخيل للعطور',
    customer_code: 'C-0004',
    date: '2026-08-25',
    due_date: '2026-10-24',
    channel: 'manual',
    warehouse_id: 'wh-001',
    warehouse_name: 'Main Warehouse',
    items: [
      {
        id: 'item-003-1',
        invoice_id: 'inv-003',
        line_number: 1,
        product_id: 'prod-001',
        product_name: 'Royal Oud Premium',
        product_name_ar: 'عود ملكي فاخر',
        product_code: 'OUD-001',
        quantity: 20,
        unit_id: 'unit-001',
        unit_symbol: 'PCS',
        unit_price: 68.000,
        line_discount_type: 'percentage',
        line_discount_value: 9.33,
        line_discount_amount: 140.000,
        line_subtotal: 1360.000,
        tax_rate: 0,
        tax_amount: 0,
        line_total: 1360.000,
        unit_cost: 45.000,
        total_cost: 900.000,
        gross_profit: 460.000,
        gross_margin_percent: 33.82,
        allocated_payment_fee: 0,
        allocated_delivery_cost: 15.000,
        allocated_marketing_cost: 0,
        allocated_other_costs: 0,
        total_commercial_costs: 15.000,
        commercial_profit: 445.000,
        commercial_margin_percent: 32.72,
        is_below_target_margin: false,
        is_negative_margin: false,
        warehouse_id: 'wh-001',
        available_stock: 60,
        stock_sufficient: true,
      },
    ],
    subtotal: 1360.000,
    invoice_discount_type: 'percentage',
    invoice_discount_value: 0,
    invoice_discount_amount: 0,
    tax_amount: 0,
    total: 1360.000,
    paid_amount: 600.000,
    outstanding: 760.000,
    payments: [
      {
        id: 'pay-003-1', invoice_id: 'inv-003', company_id: 'company-001',
        payment_number: 'PAY-2026-000082', date: '2026-08-26', amount: 600.000,
        method: 'bank_transfer', reference: 'TRF-98012', is_reversed: false,
        created_by: 'user-002', created_at: '2026-08-26T10:00:00Z',
      },
    ],
    payment_method: 'credit',
    payment_fee: 0,
    status: 'partially_paid',
    profitability: {
      invoice_id: 'inv-003',
      revenue: 1360.000,
      accounting_cogs: 900.000,
      gross_profit: 460.000,
      gross_margin_percent: 33.82,
      payment_fee: 0,
      delivery_cost: 15.000,
      marketing_cost_allocation: 0,
      other_costs: 0,
      total_commercial_costs: 15.000,
      commercial_profit: 445.000,
      commercial_margin_percent: 32.72,
      line_profitability: [],
    },
    accounting_status: 'posted',
    created_by: 'user-002',
    created_at: '2026-08-25T14:00:00Z',
    updated_at: '2026-08-26T10:00:00Z',
  },
  {
    id: 'inv-004',
    company_id: 'company-001',
    branch_id: 'branch-001',
    invoice_number: 'INV-2026-001065',
    customer_id: 'cust-003',
    customer_name: 'Fatima Al-Sabah',
    customer_name_ar: 'فاطمة الصباح',
    customer_code: 'C-0003',
    date: '2026-08-01',
    due_date: '2026-08-01',
    channel: 'pos',
    warehouse_id: 'wh-001',
    warehouse_name: 'Main Warehouse',
    items: [],
    subtotal: 150.000,
    invoice_discount_type: 'percentage',
    invoice_discount_value: 0,
    invoice_discount_amount: 0,
    tax_amount: 0,
    total: 150.000,
    paid_amount: 0,
    outstanding: 150.000,
    payments: [],
    payment_method: 'credit',
    payment_fee: 0,
    status: 'overdue',
    accounting_status: 'posted',
    created_by: 'user-004',
    created_at: '2026-08-01T10:00:00Z',
    updated_at: '2026-08-01T10:00:00Z',
  },
  {
    id: 'inv-005',
    company_id: 'company-001',
    branch_id: 'branch-001',
    invoice_number: 'INV-2026-001088',
    customer_name: 'Walk-in Customer',
    customer_name_ar: 'عميل نقدي',
    date: '2026-08-31',
    channel: 'pos',
    warehouse_id: 'wh-001',
    warehouse_name: 'Main Warehouse',
    items: [],
    subtotal: 95.000,
    invoice_discount_type: 'percentage',
    invoice_discount_value: 0,
    invoice_discount_amount: 0,
    tax_amount: 0,
    total: 95.000,
    paid_amount: 95.000,
    outstanding: 0,
    payments: [],
    payment_method: 'cash',
    payment_fee: 0,
    status: 'paid',
    accounting_status: 'posted',
    created_by: 'user-004',
    created_at: '2026-08-31T14:00:00Z',
    updated_at: '2026-08-31T14:00:00Z',
  },
];

// ═══════════════════════════════════════════════════════════════════
// DEMO DASHBOARD STATS
// ═══════════════════════════════════════════════════════════════════

export const DEMO_SALES_STATS: SalesDashboardStats = {
  period: 'thisMonth',
  total_invoices: 14,
  total_revenue: 48500.500,
  total_paid: 32300.000,
  total_unpaid: 16200.500,
  total_overdue: 3450.000,
  total_returns: 1200.000,
  gross_profit: 18950.000,
  gross_margin_percent: 39.07,
  commercial_profit: 17850.000,
  commercial_margin_percent: 36.80,
  total_cogs: 29550.500,
  cash_sales: 12400.000,
  credit_sales: 36100.500,
  count_paid: 8,
  count_unpaid: 4,
  count_overdue: 2,
  count_draft: 1,
  count_returns: 1,
  currency: 'KWD',
};

// ═══════════════════════════════════════════════════════════════════
// DEMO CREDIT NOTES
// ═══════════════════════════════════════════════════════════════════

export const DEMO_CREDIT_NOTES: CreditNote[] = [
  {
    id: 'cn-001',
    company_id: 'company-001',
    branch_id: 'branch-001',
    credit_note_number: 'CN-2026-000012',
    original_invoice_id: 'inv-003',
    original_invoice_number: 'INV-2026-001060',
    customer_id: 'cust-002',
    customer_name: 'Kuwait Gift Trading Co.',
    date: '2026-08-20',
    amount: 75.000,
    reason: 'Product damaged on delivery',
    reason_ar: 'منتج تالف عند التسليم',
    status: 'approved',
    created_by: 'user-002',
    created_at: '2026-08-20T09:00:00Z',
  },
];

// ═══════════════════════════════════════════════════════════════════
// DEMO SALES RETURNS
// ═══════════════════════════════════════════════════════════════════

export const DEMO_RETURNS: SalesReturn[] = [
  {
    id: 'ret-001',
    company_id: 'company-001',
    branch_id: 'branch-001',
    return_number: 'RET-2026-000008',
    original_invoice_id: 'inv-001',
    original_invoice_number: 'INV-2026-001055',
    customer_id: 'cust-001',
    customer_name: 'Ahmad Mohammed Al-Rashidi',
    date: '2026-08-15',
    return_type: 'partial',
    items: [
      {
        id: 'ret-item-001',
        return_id: 'ret-001',
        original_item_id: 'item-001-1',
        product_id: 'prod-003',
        product_name: 'Bakhoor Al-Malak',
        quantity: 2,
        unit_price: 18.000,
        unit_cost: 8.250,
        line_total: 36.000,
        restock: true,
        warehouse_id: 'wh-001',
      },
    ],
    subtotal: 36.000,
    total: 36.000,
    refund_method: 'cash',
    reason: 'Wrong product ordered',
    reason_ar: 'منتج خاطئ',
    status: 'completed',
    approved_by: 'user-002',
    approved_at: '2026-08-15T11:00:00Z',
    inventory_restocked: true,
    created_by: 'user-004',
    created_at: '2026-08-15T10:00:00Z',
  },
];

// Helpers
export function generateInvoiceNumber(prefix: string, nextNum: number): string {
  const year = new Date().getFullYear();
  const num = String(nextNum).padStart(6, '0');
  return `${prefix}-${year}-${num}`;
}

export function calculateLineProfitability(
  qty: number,
  unitPrice: number,
  discountAmount: number,
  unitCost: number,
  paymentFeeRate: number,
  deliveryCostAlloc: number,
): { gross_profit: number; gross_margin_percent: number; commercial_profit: number; commercial_margin_percent: number; is_below_target: boolean; is_negative: boolean } {
  const revenue = qty * unitPrice - discountAmount;
  const cogs = qty * unitCost;
  const grossProfit = revenue - cogs;
  const grossMargin = revenue > 0 ? (grossProfit / revenue) * 100 : 0;
  const paymentFee = revenue * paymentFeeRate;
  const commercialCosts = paymentFee + deliveryCostAlloc;
  const commercialProfit = grossProfit - commercialCosts;
  const commercialMargin = revenue > 0 ? (commercialProfit / revenue) * 100 : 0;
  return {
    gross_profit: grossProfit,
    gross_margin_percent: grossMargin,
    commercial_profit: commercialProfit,
    commercial_margin_percent: commercialMargin,
    is_below_target: grossMargin < 30 && grossMargin >= 0,
    is_negative: grossMargin < 0,
  };
}
